---
# ----------------------------------------
# Тестовый проектный файл для RDEV 2019
# ----------------------------------------
project:
  start: main/usr.json  # файл - с которого можно начать чтение, в нем могут быть ссылки на другие файлы

  name: empty_project     # уникальное имя проекта 
